# -*- coding: utf-8 -*-
# Datos de las canciones de Arnau (nivel 7 anios). Contenido sencillo pero real.
CDO=[("Do","1","I · casa"),("Re","2","II"),("Mi","3","III"),("Fa","4","IV"),
     ("Sol","5","V · imán"),("La","·","VI"),("Si","·","VII"),("Do","·","VIII")]

SONGS=[
 {
  "title":"Baa Baa Black Sheep","composer":"Canción tradicional · arr. Jim Paterson",
  "score":"src/Baa Baa Black Sheep.pdf","video":"69KUnCs_460","level":"1",
  "specs":{"ton":"Do mayor","comp":"4/4","tempo":"Alegre · ♩≈ 96","forma":"A–A–B–B","dif":"Muy fácil","manos":"Melodía + acordes"},
  "obra":"Es una canción muy antigua de una ovejita negra que tiene lana calentita para llenar <b>tres sacos</b>. ¡Su melodía es la misma que <b>Estrellita, dónde estás</b>! Se toca en <b>DO</b>, la nota más fácil de encontrar, así que es perfecta para empezar.",
  "ton_title":"Tu tonalidad: DO mayor (¡solo teclas blancas!)",
  "ton_txt":"En DO mayor no hay teclas negras: todo son blancas. La nota <b>DO</b> es la «casa» (donde descansa la canción) y <b>SOL</b> es el «imán» que tira para volver a casa.",
  "scale":CDO,
  "two":[("Las notas que usas","Solo estas: <b>Do, Re, Mi, Fa, Sol y La</b>. Búscalas en tu piano antes de tocar."),
         ("El ritmo","Hay <b>negras</b> (duran 1 tiempo) y <b>blancas</b> (duran 2). Cuenta en voz alta: 1-2-3-4.")],
  "tec_title":"la posición de DO y los 3 acordes",
  "tec_lede":"Pon la mano derecha en <b>posición de DO</b> (un dedo en cada tecla) y usa la izquierda para los 3 acordes: DO, FA y SOL.",
  "warm_title":"Calentamiento · la posición de DO",
  "warm_txt":"Coloca el dedo <b>1</b> (pulgar) en DO y ve poniendo un dedo en cada tecla hasta el <b>5</b> en SOL. Toca subiendo y bajando muy despacio.",
  "kbd":{"Do":1,"Re":2,"Mi":3,"Fa":4,"Sol":5},
  "kbd_cap":"Posición de DO: dedo 1 en Do, 2 en Re, 3 en Mi, 4 en Fa y 5 en Sol.",
  "steps":[("Encuentra el DO.","Está a la izquierda de las 2 teclas negras juntas. Tócalo 3 veces.",""),
           ("Toca la melodía sola.","Mano derecha: Do-Do-Sol-Sol-La-La-Sol. Despacito.","♩ = 60"),
           ("Añade los acordes.","Mano izquierda: DO, luego FA, luego SOL, un acorde por compás.",""),
           ("Junta las dos manos.","Primero muy lento; cuando salga, un poco más rápido.","♩ = 80")],
  "hard":{"cc":"cc. 5–8","tt":"El cambio de acordes","reto":"Cambiar la mano izquierda de DO a FA a SOL sin parar la melodía.","truco":"Practica solo la izquierda: DO-FA-SOL-DO muy lento, mirando dónde va la mano."},
  "interp":"Tócala <b>alegre y saltarina</b>, como una ovejita contenta. No corras: es mejor lento y sin fallos que rápido y con tropiezos.",
  "goals":["Encuentro el DO sin ayuda.","Toco la melodía con la mano derecha.","Hago los acordes DO, FA y SOL con la izquierda.","Junto las dos manos despacio."],
  "meta":"Meta de hoy: tocar el principio con las dos manos, ¡sin prisa!",
  "ex":[
    {"k":"pos","lvl":1,"title":"Posición de 5 dedos en DO","instr":"Sube y baja; un dedo por tecla (mira los números).",
     "abc":"X:1\nM:4/4\nL:1/4\nK:C\nC D E F|G F E D|C4|]\nw:1 2 3 4 5 4 3 2 1"},
    {"k":"mel","lvl":2,"title":"La melodía (mano derecha)","instr":"El principio de la canción. Debajo tienes el nombre de cada nota.",
     "abc":"X:1\nM:4/4\nL:1/4\nK:C\nC C G G|A A G2|F F E E|D D C2|]\nw:Do Do Sol Sol La La Sol Fa Fa Mi Mi Re Re Do"},
    {"k":"cho","lvl":2,"title":"Los 3 acordes (mano izquierda)","instr":"Toca los tres acordes juntos, en clave de Fa.",
     "abc":"X:1\nM:4/4\nL:1/4\nK:C clef=bass\n[C,E,G,]2 [F,A,C]2|[G,B,D]2 [C,E,G,]2|]\nw:DO FA SOL DO"},
    {"k":"rit","lvl":1,"title":"El ritmo (palméalo primero)","instr":"Da palmadas contando 1-2-3-4; luego tócalo en la nota DO.",
     "abc":"X:1\nM:4/4\nL:1/4\nK:C\nC C C C|C C C2|]\nw:1 2 3 4 1 2 3-4"},
  ],
 },
 {
  "title":"The Wheels on the Bus","composer":"Canción tradicional · arr. Jim Paterson",
  "score":"src/ The Wheels on the Bus.pdf","video":"U_osX4AHUs0","level":"1",
  "specs":{"ton":"Do mayor","comp":"4/4","tempo":"Marcha alegre · ♩≈ 100","forma":"Estrofa que se repite","dif":"Muy fácil","manos":"Melodía + acordes"},
  "obra":"«Las ruedas del autobús giran y giran» es una canción de juegos con gestos. Cada estrofa repite lo mismo cambiando la letra (las puertas, los limpiaparabrisas…). Se toca en <b>DO mayor</b> y su ritmo es como una <b>marcha</b>: perfecta para llevar el pulso con el pie.",
  "ton_title":"Tu tonalidad: DO mayor",
  "ton_txt":"Todo en teclas blancas. La canción va y viene entre dos acordes fáciles: <b>DO</b> (la casa) y <b>FA</b>. Reconocer cuándo cambia te dice cuándo mover la mano izquierda.",
  "scale":CDO,
  "two":[("Las notas que usas","Do, Re, Mi, Fa, Sol y La. El salto de <b>Do a Fa</b> aparece mucho: practícalo."),
         ("El ritmo","Es una <b>marcha</b> en 4/4. Marca el pulso con el pie: 1-2-3-4, firme y regular.")],
  "tec_title":"el salto Do–Fa y el pulso de marcha",
  "tec_lede":"Hoy trabajamos el <b>salto de DO a FA</b> en la mano derecha y llevar un <b>pulso firme</b>, como un autobús que no se para.",
  "warm_title":"Calentamiento · el salto Do–Fa",
  "warm_txt":"Toca <b>DO</b> con el pulgar (1) y salta a <b>FA</b> con el dedo 4, ida y vuelta, sin mirar. Cuenta 1-2-3-4 mientras saltas.",
  "kbd":{"Do":1,"Fa":4},
  "kbd_cap":"El salto de DO (dedo 1) a FA (dedo 4): el movimiento que más se repite en la canción.",
  "steps":[("Marca el pulso.","Sin tocar, da palmadas 1-2-3-4 como una marcha, firme y regular.",""),
           ("Melodía sola.","Mano derecha, muy despacio, respetando el salto Do-Fa.","♩ = 66"),
           ("Los acordes.","Mano izquierda: DO y FA, cambiando a tiempo.",""),
           ("Manos juntas.","Une melodía y acordes llevando el pulso con el pie.","♩ = 90")],
  "hard":{"cc":"cc. 1–4","tt":"El salto de Do a Fa","reto":"Llegar a la tecla FA sin mirar y sin frenar la marcha.","truco":"Repite solo el salto Do-Fa-Do-Fa diez veces, cada vez más seguro, hasta que la mano lo haga sola."},
  "interp":"Tócala <b>alegre y con marcha</b>, como si el autobús fuera lleno de niños cantando. El pulso siempre igual: ¡el autobús no acelera ni frena de golpe!",
  "goals":["Llevo un pulso firme de marcha.","Hago el salto Do-Fa sin mirar.","Cambio los acordes DO y FA a tiempo.","Toco una estrofa entera con las dos manos."],
  "meta":"Meta de hoy: una estrofa con las dos manos y el pulso firme.",
  "ex":[
    {"k":"pos","lvl":1,"title":"Posición de 5 dedos en DO","instr":"Calentamiento: sube y baja, un dedo por tecla.",
     "abc":"X:1\nM:4/4\nL:1/4\nK:C\nC D E F|G F E D|C4|]\nw:1 2 3 4 5 4 3 2 1"},
    {"k":"salto","lvl":2,"title":"El salto Do–Fa","instr":"Salta del pulgar (Do) al dedo 4 (Fa), ida y vuelta.",
     "abc":"X:1\nM:4/4\nL:1/4\nK:C\nC F C F|C F C2|F C F C|F C F2|]\nw:Do Fa Do Fa Do Fa Do Do Fa Do Fa Do Fa Do"},
    {"k":"cho","lvl":2,"title":"Los acordes DO y FA (mano izquierda)","instr":"Cambia entre los dos acordes, en clave de Fa.",
     "abc":"X:1\nM:4/4\nL:1/4\nK:C clef=bass\n[C,E,G,]2 [F,A,C]2|[C,E,G,]2 [F,A,C]2|]\nw:DO FA DO FA"},
    {"k":"rit","lvl":1,"title":"El ritmo de marcha","instr":"Palmea 1-2-3-4 firme; luego tócalo en DO.",
     "abc":"X:1\nM:4/4\nL:1/4\nK:C\nC C C C|C C C C|]\nw:1 2 3 4 1 2 3 4"},
  ],
 },
]
