// Mapa de cobertura del Libro de marca: UNA entrada por pregunta del
// cuestionario (PLAN360_NEGOCIO_AREAS), en el mismo orden.
//   'd'              → está en una página principal de diseño
//   ['T', etiqueta]  → campo de texto en la ficha detallada
//   ['S', etiqueta]  → Sí / Parcial / No + nota
//   ['L', etiqueta]  → lista de 3
//   ['N', etiqueta, unidad] → cifra
//   ['C', etiqueta, [puntos]] → checklist
const T = (l) => ['T', l], S = (l) => ['S', l], L = (l) => ['L', l], N = (l, u) => ['N', l, u], C = (l, i) => ['C', l, i];

export const COBERTURA = {
  'Concepto': {
    'Misión, visión y valores': ['d', 'd', 'd', 'd'],
    'Propuesta única de valor': ['d'],
    'Posicionamiento competitivo': ['d', 'd'],
    'Competidores directos e indirectos (DAFO)': ['d', 'd', 'd', 'd', 'd'],
    'Clientes actual vs. cliente objetivo': ['d', 'd', 'd'],
    'Síntesis del DAFO': ['d'],
    'Customer journey — por etapa': ['d', 'd', 'd'],
  },
  'Marca': {
    'Brand book': ['d', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd'],
    'Customer journey': ['d'],
  },
  'Cocina': {
    'Conociendo más sobre tu estilo culinario': ['d', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd'],
    'Formato y estructura de la oferta de comida': ['d', 'd', 'd', 'd', 'd', 'd',
      T('Cómo probamos un plato nuevo antes de lanzarlo y cómo medimos si gusta'),
      T('Dónde y cómo se comunican las sugerencias del día')],
    'Experiencias y formatos especiales': ['d', T('Canales de venta alternativos'), 'd', 'd', 'd', 'd', 'd'],
    'Menú engineering': ['d', T('Mapa de calor de la carta: zonas que más se miran y dónde va el plato estrella')],
    'Gestión de proveedores': ['d',
      S('Proveedores de emergencia por sección'), S('Contratos o condiciones por escrito'),
      T('Frecuencia de revisión de precios'), S('Listado e histórico de precios por proveedor'),
      'd', 'd',
      T('Protocolo de recepción, paso a paso'),
      S('Factura y albarán se cotejan al recibir'), S('Se pesa lo que va a peso'),
      S('Se controla la temperatura del fresco'), S('Se revisan caducidades del seco'),
      T('Controles de calidad y su frecuencia')],
  },
  'Sala': {
    'Formato y dinámica de la oferta de bebidas': ['d', T('Cómo se organiza la carta de vinos'), 'd', 'd', 'd',
      T('Cómo se organiza la carta de licores'), 'd', T('Bebidas de autor o clásicos'), 'd'],
    'Presentación general y storytelling': [T('Composición de la mesa'), T('Botellas y barriles a la vista'), 'd',
      T('Estímulos que completan la experiencia (velas, centros, plantas…)'), 'd', 'd', 'd',
      T('Recursos para contar nuestra historia'), T('Momentos del servicio en los que mostramos procesos')],
    'Menú engineering': [['M', 'Menú engineering de bebidas']],
    'Cierre de servicio y fidelización': ['d', 'd', 'd', 'd', 'd'],
  },
  'Equipo': {
    'RRHH': ['d', T('Formación técnica necesaria por puesto'), T('Formación de cocina: últimos 3 cursos y fechas'), T('Cómo se refuerza el personal en picos de demanda')],
    'Visión, liderazgo y coherencia estratégica': [S('La visión y los valores se comunican con claridad'), S('Las decisiones son coherentes con lo que se dice'),
      S('El propietario está presente y accesible en servicio'), S('Prioridades del día alineadas con la estrategia'), S('Revisión semanal de cultura y rendimiento')],
    'Reclutamiento, selección y ajuste cultural': [S('Perfiles de puesto con ajuste cultural'), S('Pruebas prácticas en la selección'),
      S('Onboarding estructurado'), S('Seguimiento a los 15, 30 y 60 días'), S('Banco de candidatos para ausencias')],
    'Formación, desarrollo y carrera': [S('Presupuesto y calendario anual de formación'), S('Formación según carencias detectadas'), S('Rutas de desarrollo profesional')],
    'Gestión del rendimiento, compensación y retención': [S('Detección temprana de rotación'), S('KPIs de rendimiento individual y de equipo'),
      S('Revisión de salarios frente al mercado'), S('Bonus o mejoras para retener')],
    'Cultura, reconocimiento y bienestar': [S('El día a día refleja los valores'), S('Reconocimiento regular y visible'),
      S('Se pueden contar ideas y errores sin miedo'), S('Iniciativas de clima y cohesión'), S('Se miden rotación, ausencias y bajas')],
    'Comunicación operativa, procesos HR y datos': [S('Briefing previo al servicio estandarizado'), S('Protocolo de comunicación sala-cocina'),
      S('Sistema que integra los turnos'), S('Seguimiento de KPIs de RRHH')],
    'eNPS y preguntas abiertas': ['d', 'd', 'd', T('Indicadores que dirán si las acciones de RRHH funcionan'), T('Prioridad de cultura y liderazgo frente a otras iniciativas')],
    'Preguntas abiertas': [L('Tres cambios organizativos urgentes'), 'd', T('Información que aún necesitamos del equipo')],
  },
  'Gestión': {
    'Catalogación de costes y contabilidad operativa': [T('Costes fijos mensuales por partida'), N('Nóminas: bruto y cargas sociales', '€ / mes'),
      N('Materia prima', '€ / mes'), T('Gastos administrativos recurrentes y destino'), T('Otros gastos recurrentes'),
      S('Plan de amortizaciones'), T('Cuentas contables y frecuencia de actualización'), T('Cómo se controlan ventas y gastos')],
    'Punto de equilibrio': ['d', 'd', 'd'],
    'Gestión de tesorería y forecast': ['d', T('Plazo medio de pago a proveedores y condiciones'), T('Líneas de crédito y condiciones'),
      T('Previsión de ventas a 12 semanas'), N('Retiradas del propietario', '€ / mes'), 'd'],
    'CAPEX, mantenimiento y provisiones extraordinarias': ['d', T('Reparaciones mayores del último año y coste'), T('Fondo de reserva y cómo se dota'),
      T('Activos en leasing y en propiedad'), T('Criterio para priorizar inversiones')],
    'Controles internos y plan de acción': [T('Informes que se generan y quién los recibe'), T('Límites de aprobación para compras y contrataciones'), 'd',
      T('Elasticidad de precios estimada'), T('Promociones o canales que suben cubiertos sin disparar costes'), N('Ahorro estimado optimizando personal y compras', '€ / mes')],
    'Plantillas y entrada de datos': [S('Hojas de datos del negocio completadas')],
    'Operaciones en cocina': [T('Checklist de apertura y cierre'), S('Fichas técnicas disponibles para el equipo'), N('Platos que requieren producción previa', '%'),
      N('Capacidad máxima sin perder calidad', 'cubiertos / hora'), N('Tiempo medio de salida de un plato', 'min'), T('Gestión y reducción de mermas'),
      'd', T('Plato que más margen deja y el que más tiempo consume'), L('Tres mejoras de cocina en 30 días'), 'd'],
    'Operaciones en sala': [T('Reservas y overbooking'), 'd', 'd', N('Tiempo objetivo de bebidas', 'min'), 'd',
      T('Frases estándar: bienvenida, recomendación, postre y copa'), T('Cómo se hacen las sugerencias de venta'), T('Roles de comunicación cocina-sala'),
      T('Registro y respuesta a incidencias en mesa'), S('Protocolo de alergias e intolerancias'), T('Herramientas para comandar y cobrar'),
      T('Cómo medimos la satisfacción'), T('Objetivos comerciales por mesa o turno'), T('Formación de sala: últimos 3 cursos y fechas'),
      S('Role-plays y simulacros de atención'), T('Qué hacemos cuando la cocina se retrasa'), T('Refuerzo de sala en picos de demanda'),
      S('Guiones de venta por oferta'), L('Tres mejoras de sala en 30 días'), 'd'],
    'Operaciones de gestión': [T('Cómo se garantiza el pago de impuestos'), T('Criterio para priorizar pagos a proveedores'), T('Reparto diario de ingresos para cubrir fijos'),
      T('Previsión de tesorería y medidas ante un déficit'), T('Política de provisiones para imprevistos'), 'd', 'd',
      C('Revisión diaria', ['Objetivos e incidencias', 'Turnos y sustituciones', 'Reservas y ocupación', 'Servicio y satisfacción', 'Cierre del día: KPIs y caja']),
      C('Revisión mensual', ['Cierre contable', 'Cashflow y previsión', 'Conciliación y arqueos', 'Nóminas', 'Gestión fiscal', 'Inventario físico', 'Escandallos y precios', 'Evaluación de proveedores', 'Mantenimiento preventivo', 'Formación y evaluación', 'Marketing y ventas', 'KPIs operativos', 'Planificación de compras', 'Resumen y plan de acción', 'Cuenta de resultados', 'Obligaciones legales'])],
    'Cumplimiento normativo': [S('Licencia de actividad y registro sanitario'), S('Política de cumplimiento firmada'), S('Boletín eléctrico y certificados de instalaciones'),
      S('Accesibilidad y movilidad reducida'), S('Salida de humos certificada'), S('Evacuación, señalización e iluminación de emergencia'),
      S('Extintores y sistemas de supresión'), S('Baños suficientes y en condiciones'), S('Seguro de responsabilidad civil'),
      S('Cartelería obligatoria visible'), T('Inspecciones o sanciones en los últimos 24 meses')],
    'Seguridad alimentaria': [S('Plan APPCC documentado y actualizado'), S('Mantenimiento preventivo de equipos críticos'), S('Plan de limpieza general'),
      T('Frecuencia de registro de temperaturas'), S('Procedimiento escrito de alérgenos'), S('Sala formada en alérgenos'),
      S('Manipuladores registrados con formación vigente'), S('Control de plagas con contrato y registros'), S('Gestión de residuos al día'),
      S('Análisis periódico del agua'), S('Muestras testigo de producciones críticas'), S('Trazabilidad de productos y proveedores'),
      S('Auditorías de seguridad alimentaria'), T('Inspecciones de sanidad en 24 meses y resultado')],
    'Sistemas centrales': ['d', T('Módulos del TPV activos'), S('Informes automáticos del TPV'), T('Formas de pago en efectivo'),
      T('Terminales de pago con tarjeta'), N('Ventas con tarjeta frente a efectivo', '% / %'), T('Cómo se hace el arqueo diario'),
      T('Datos que el TPV exporta a contabilidad'), S('TPV adaptado a la normativa fiscal'), T('Apps de sala y estaciones'),
      T('Cómo llegan las comandas a cocina'), T('Problema recurrente del TPV')],
    'Gestión de reservas': ['d', T('Reservas por canal'), S('Reservas registradas automáticamente'), T('Datos que se recogen en la reserva'),
      S('Confirmaciones y recordatorios automáticos'), T('Cambios y cancelaciones'), T('Depósito para grupos y tasa real de no-show'),
      T('Qué hace la sala ante el overbooking'), T('Mejora de reservas en 30 días')],
    'CRM y gestión de datos': ['d', T('Cómo se alimenta la base de datos'), T('Datos mínimos de la ficha de cliente'), S('Consentimiento RGPD en la reserva'),
      T('Segmentos activos'), T('Automatizaciones que salen del CRM'), T('Frecuencia, canal y respuesta de las comunicaciones'),
      T('Cómo medimos si una campaña trae reservas'), S('Historial de interacciones por cliente'), T('Dos usos del CRM prioritarios a 90 días')],
    'Inventarios y compras': ['d', T('Frecuencia de inventario'), S('Inventario integrado con el TPV'), T('Sistema de compras recurrentes'), T('Facturas y tickets: nube o papel')],
    'Dashboards y KPIs operativos': ['d', T('KPIs semanales y quién los revisa'), T('Métricas diarias: exportación o nube')],
    'Acceso, backups y seguridad básica': [T('Quién accede al TPV, reservas y CRM'), S('Cuentas individuales con permisos'), S('Copias de seguridad periódicas')],
    'Impacto y prioridades': ['d', T('La mejora tecnológica de los próximos 30 días'), N('Presupuesto anual en tecnología', '€')],
  },
  'Captación': {
    'Marketing': ['d', T('Quién decide el marketing y cuántas horas le dedica'), 'd', 'd', S('Dominio y correo profesional'),
      S('Web y redes con carta, horario y botón de reserva'), 'd', S('Calendario editorial'), T('Contenido que mejor funciona'),
      'd', 'd', T('Oferta de captación para nuevos clientes'), T('Qué nos impide hacer buen marketing'), 'd', S('Carta adaptada al móvil'), S('Stories periódicas del día a día')],
    'Fidelización': ['d', T('Automatizaciones para clientes recurrentes'), 'd', S('Segmentos de clientes recurrentes'), 'd',
      T('Cómo medimos el éxito de la fidelización'), T('Cómo se enlazan visitas y recompensas en el TPV'), 'd', L('Tres acciones para aumentar la recurrencia')],
    'Prueba social': ['d', T('Quién responde las reseñas y en cuánto tiempo'), S('Protocolo escrito de reseñas'), S('Pedimos reseñas activamente'),
      S('Incentivos por reseña'), 'd', S('Usamos contenido de clientes'), T('Colaboraciones con influencers o prensa local'),
      T('Colaboraciones locales'), 'd'],
  },
  'Tú al frente': {
    'Preguntas abiertas': ['d', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd', 'd'],
  },
};
