#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Genera EJERCICIOS en pentagrama (Verovio) propios de cada pieza.
Cuatro ejercicios por obra, dificultad progresiva (nivel 1-4), largos y
tipo estudio, sobre aspectos reales de la partitura. Alterna mano derecha
(clave de Sol) e izquierda (clave de Fa).
Escribe notation/ex_<id>.png y exercises.json."""
import verovio, cairosvg, io, os, json
from PIL import Image

os.makedirs("notation", exist_ok=True)
tk = verovio.toolkit()

def render(abc, name, w=1500, scale=38):
    tk.setOptions({"inputFrom":"abc","adjustPageHeight":True,"pageWidth":w,"scale":scale,
        "footer":"none","header":"none","pageMarginTop":6,"pageMarginBottom":6,
        "pageMarginLeft":6,"pageMarginRight":6})
    tk.loadData(abc); svg=tk.renderToSVG(1)
    png=cairosvg.svg2png(bytestring=svg.encode(), output_width=int(w*1.35))
    im=Image.open(io.BytesIO(png)).convert("RGBA")
    gray=Image.alpha_composite(Image.new("RGBA",im.size,(255,255,255,0)),im).convert("L")
    bbox=gray.point(lambda p:0 if p>245 else 255).getbbox()
    if bbox:
        m=12; b=(max(0,bbox[0]-m),max(0,bbox[1]-m),min(im.size[0],bbox[2]+m),min(im.size[1],bbox[3]+m)); im=im.crop(b)
    out=Image.new("RGB",im.size,(255,255,255)); out.paste(im,mask=im.split()[3])
    out.save("notation/"+name); return out.size

def buildabc(M,L,K,body):
    return f"X:1\nM:{M}\nL:{L}\nK:{K}\n{body}"

# (base, id, nivel[1-4], titulo, instruccion, M, L, K, body)
EX = [
 # ==================== FUNDAMENTOS ====================
 ("Himno de la Alegría","himno1",1,"Cinco dedos en Do","Calentamiento: un dedo por tecla, sonido parejo y mano relajada.",
   "4/4","1/4","C","C D E F G F E D|C D E F G F E D|E F G A B A G F|E D C2 z2|]"),
 ("Himno de la Alegría","himno2",2,"Grados conjuntos ligados","Estudio de legato por notas vecinas: liga cada grupo sin cortar, en oleadas.",
   "4/4","1/4","C","(C D E F)|(E F G A)|(G A B c)|(B c d e)|(e d c B)|(c B A G)|(A G F E)|(F E D C)|]"),
 ("Himno de la Alegría","himno3",3,"Escala de Do a dos octavas","Sube dos octavas y baja en corcheas; velocidad y peso iguales, ida y vuelta.",
   "4/4","1/8","C","C D E F G A B c|d e f g a b c' d'|d' c' b a g f e d|c B A G F E D C|]"),
 ("Himno de la Alegría","himno4",4,"Estudio de terceras","Terceras quebradas subiendo dos octavas: suelta la mano y afina la igualdad.",
   "4/4","1/8","C","C E D F E G F A|G B A c B d c e|d f e g f a g b|c'4 z4|]"),
 ("Yankee Doodle","yankee1",1,"Notas repetidas con cambio de dedo","Repite cada nota con dedos 3-2-1-3 subiendo la escala; ágil y ligero.",
   "4/4","1/4","C","C C C C|D D D D|E E E E|F F F F|G G G G|A A A A|B B B B|c c c c|]"),
 ("Yankee Doodle","yankee2",2,"Saltos de quinta y octava","Trabaja los saltos abiertos sin mirar; cada llegada, limpia.",
   "4/4","1/4","C","C G C G|E c E c|G d G d|c g c g|G c E G|c e G c|E G C E|C4|]"),
 ("Yankee Doodle","yankee3",3,"El tema completo","La melodía de Yankee Doodle; pulso de marcha binario, sin correr.",
   "4/4","1/4","C","G G A B|G B A2|G G A B|G2 F2|E c B G|A B c2|G G A B|c2 z2|]"),
 ("Yankee Doodle","yankee4",4,"Saltos rápidos en corcheas","Estudio de saltos en corcheas por los acordes; muñeca suelta y precisión.",
   "4/4","1/8","C","C G E G C G E G|D A F A D A F A|E c G c E c G c|C G E G C4|]"),
 ("Alouette","alou1",1,"Staccato de muñeca","Escala staccato subiendo y bajando; notas cortas, secas y parejas.",
   "4/4","1/4","C",".C .D .E .F|.G .A .B .c|.c .B .A .G|.F .E .D .C|.C .E .G .E|.C .E .G .c|.G .E .C2|]"),
 ("Alouette","alou2",2,"Legato y staccato alternando","Un compás ligado, el siguiente picado, subiendo: domina las dos articulaciones.",
   "4/4","1/4","C","(C D E F)|.G .F .E .D|(E F G A)|.B .A .G .F|(G A B c)|.d .c .B .G|(C E G c)|c4|]"),
 ("Alouette","alou3",3,"La forma A–B–A en corcheas","Motivo ágil que sube y baja; trabaja el cambio de dirección sin frenar.",
   "4/4","1/8","C","G E C E G c G E|F D B, D F A F D|E C G, C E G E C|G, C E G c e g2|]"),
 ("Alouette","alou4",4,"Pregunta y respuesta","Cuatro compases fuertes (pregunta) y cuatro suaves (respuesta): fraseo en diálogo.",
   "4/4","1/4","C","G A G E|C E G2|A B A F|D F A2|G E C E|G c e2|d c B G|C4|]"),
 ("Top Gun (Anthem)","topgun1",1,"Acordes en bloque","Progresión I-IV-V-I; ataca las tres notas exactamente juntas, con sonido firme.",
   "4/4","1/4","C","[CEG][CEG][CEG][CEG]|[FAc][FAc][FAc][FAc]|[GBd][GBd][GBd][GBd]|[CEG]2 [CEG]2|[FAc]2 [GBd]2|[CEG]4|]"),
 ("Top Gun (Anthem)","topgun2",2,"Desgranar los acordes","Los acordes I-IV-V rotos, subiendo y bajando; conoce cada uno por dentro.",
   "4/4","1/4","C","C E G c|G E C2|F A c f|c A F2|G B d g|d B G2|C E G c|c G E C|]"),
 ("Top Gun (Anthem)","topgun3",3,"Acordes con bajo (clave de Fa)","La mano izquierda sostiene el bajo y el acorde; sonido épico y pleno.",
   "4/4","1/4","C","[K:clef=bass] C,, [C,E,G,] [C,E,G,]2|F,, [F,A,C] [F,A,C]2|G,, [G,B,D] [G,B,D]2|C,, [C,E,G,]2 z|]"),
 ("Top Gun (Anthem)","topgun4",4,"Octavas en bloque","Estudio de octavas y acordes alternos; potencia sin endurecer el brazo.",
   "4/4","1/4","C","[Cc][Cc] [Ee][Ee]|[Gg][Gg] [cc']2|[Ff][Ff] [Aa][Aa]|[cc']2 z2|[Gg] [Bb] [dd'] [Gg]|[Cc]4|]"),
 ("Tetris (Korobéiniki)","tetris1",1,"Ostinato de la izquierda","El patrón grave que sostiene la pieza, moviendo la armonía; clave de Fa.",
   "4/4","1/4","Am","[K:clef=bass] A,,2 E,2|A,,2 E,2|D,2 A,2|D,2 A,2|E,2 B,2|E,2 B,2|A,,2 E,2|A,,4|]"),
 ("Tetris (Korobéiniki)","tetris2",2,"El tema completo en La menor","La melodía de Korobéiniki; articula con claridad y buen pulso.",
   "4/4","1/4","Am","e2 B c|d2 c B|A2 A c|e2 d c|B2 z B|c d e2|c2 A2|A4|]"),
 ("Tetris (Korobéiniki)","tetris3",3,"El tema en corcheas","La versión ágil del tema; mantén el pulso firme al aumentar la velocidad.",
   "4/4","1/8","Am","e2 B c d2 c B|A2 A c e2 d c|B2 z2 c d e2|c2 A4 z2|]"),
 ("Tetris (Korobéiniki)","tetris4",4,"Escala menor con salto de registro","Sube la escala de La menor y salta a la octava; velocidad y agilidad.",
   "4/4","1/8","Am","A, B, C D E F G A|A e A e A E A, E|d c B A G F E D|C A, C E A2 z2|]"),
 ("Oh, When the Saints","saints1",1,"La anacrusa","Arranca en anacrusa: las tres notas de impulso caen ANTES del «1». Cuenta «…2-3-4».",
   "4/4","1/4","G","G B c|d2 d2|c2 A2|B2 G2|c2 c2|c2 A2|B2 d2|c2 B2|G4|]"),
 ("Oh, When the Saints","saints2",2,"Acordes I-IV-V (clave de Fa)","Los tres pilares de Sol mayor encadenados; cambia a tiempo con la izquierda.",
   "4/4","1/4","G","[K:clef=bass] [G,,B,,D,]2 [C,E,G,]2|[D,F,A,]2 [G,,B,,D,]2|[G,,B,,D,] [C,E,G,] [D,F,A,] [G,,B,,D,]|[C,E,G,]2 [D,F,A,]2|[G,,B,,D,]4|]"),
 ("Oh, When the Saints","saints3",3,"Escala de Sol con Fa#","La escala de la tonalidad a dos octavas en corcheas; no olvides el Fa#.",
   "4/4","1/8","G","G A B c d e ^f g|a b c' d' e' ^f' g'2|g' ^f' e' d' c' b a g|^f e d c B A G2|]"),
 ("Oh, When the Saints","saints4",4,"Bajo caminante con anacrusa","Estudio con anacrusa y bajo que camina; el swing festivo de Nueva Orleans.",
   "4/4","1/4","G","D|G B d B|c A F2|G B d g|d B G2|c A d B|G F E2|D G B G|G4|]"),
 ("La Pantera Rosa","panther1",1,"Escala cromática","Estudio cromático: sube medio tono a medio tono al agudo y baja igual; parejo.",
   "4/4","1/8","Am","A ^A B c ^c d ^d e|f ^f g ^f f e ^d e|a ^g g ^f f e ^d d|^c c B ^A A2 z2|]"),
 ("La Pantera Rosa","panther2",2,"Saltos de octava en staccato","Sube por la escala saltando octavas, corto y preciso; el gato que acecha.",
   "4/4","1/4","Am",".A, .A .A, .A|.B, .B .B, .B|.C .c .C .c|.D .d .D .d|.E .e .E .e|.A, .A .A,2|]"),
 ("La Pantera Rosa","panther3",3,"Cromatismo con silencios","El motivo felino: notas cromáticas y silencios que acechan; lo que no suena cuenta.",
   "4/4","1/8","Am","A2 z ^A B2 z c|^c2 z d ^d2 z e|e z ^d z d z ^c z|A4 z4|]"),
 ("La Pantera Rosa","panther4",4,"Cromática en semicorcheas","Estudio veloz cromático; ligero y misterioso, sin acentos.",
   "4/4","1/16","Am","A ^A B c ^c d ^d e f ^f g ^g a ^a b c'|c' b ^a a ^g g ^f f e ^d d ^c c B ^A A|]"),
 ("El Submarino Amarillo","submarine1",1,"Mano derecha legato","Línea larga y ligada, sin cortar el sonido entre notas; el canto de la melodía.",
   "4/4","1/4","G","(G A B c)|(d e d c)|(B c d e)|(f g f e)|(d c B A)|(G A B G)|(c B A G)|(G2 z2)|]"),
 ("El Submarino Amarillo","submarine2",2,"Mano izquierda staccato","El acompañamiento picado y saltarín en clave de Fa; corto, con rebote de muñeca.",
   "4/4","1/4","G","[K:clef=bass] .G, .D .G, .D|.C .G, .C .G,|.D, .A, .D, .A,|.G, .D .G,2|.G, .B, .D .B,|.G,4|]"),
 ("El Submarino Amarillo","submarine3",3,"El estribillo","La melodía del estribillo; cántala mientras la tocas, alegre y rítmica.",
   "4/4","1/4","G","d d c B|A G2 z|d d c B|A2 z2|G A B c|d2 B2|A B A G|G4|]"),
 ("El Submarino Amarillo","submarine4",4,"Coordinar las dos articulaciones","Corcheas ligadas y picadas alternas en el mismo compás; cada gesto, claro.",
   "4/4","1/8","G","(G A) .B .c (d e) .f .g|(a g) .f .e (d c) .B .A|(G A) .B .c (d e) .d .B|(G2) z2 z4|]"),
 ("Ejercicios a cuatro manos","fourhands1",1,"Terceras paralelas","Dos notas de tercera a la vez, subiendo y bajando; deben sonar exactamente juntas.",
   "4/4","1/4","C","[CE][DF][EG][FA]|[GB][Ac][Bd][ce]|[df][eg][fa][gb]|[ac']2 [gb]2|[fa][eg][df][ce]|[Bd][Ac][GB][FA]|[EG][DF][CE]2|]"),
 ("Ejercicios a cuatro manos","fourhands2",2,"Escala al unísono, dos octavas","La misma escala en octavas; sincronía perfecta arriba y abajo.",
   "4/4","1/4","C","C D E F|G A B c|d e f g|a b c'2|c' b a g|f e d c|B A G F|E D C2|]"),
 ("Ejercicios a cuatro manos","fourhands3",3,"Movimiento contrario","Estudio de manos en espejo: la línea abre y cierra desde el centro (dos voces).",
   "4/4","1/4","C","[Gc][Fd][Ee][Df]|[Cg][B,a][A,b][G,c']|[A,b][B,a][Cg][Df]|[Ee][Fd][Gc][G,c']|]"),
 ("Ejercicios a cuatro manos","fourhands4",4,"Escala en octavas","Estudio de octavas a dos manos; ataca las dos notas exactamente juntas.",
   "4/4","1/4","C","[C,c][D,d][E,e][F,f]|[G,g][A,a][B,b][C c']|[C c'][B,b][A,a][G,g]|[F,f][E,e][D,d][C,c]|]"),
 # ==================== DESARROLLO ====================
 ("Jingle Bells","jingle1",1,"El acorde de Sol y sus inversiones","Recorre el acorde en fundamental y sus inversiones, con el mínimo movimiento.",
   "4/4","1/4","G","[G,B,D]2 [B,DG]2|[DGB]2 [Gdg]2|[Gdg]2 [DGB]2|[B,DG]2 [G,B,D]2|[G,B,D] [B,DG] [DGB] [Gdg]|[G,B,D]4|]"),
 ("Jingle Bells","jingle2",2,"El tema completo","La estrofa de Jingle Bells; nota repetida pareja y el salto Re-Sol medido.",
   "4/4","1/4","G","B B B2|B B B2|B d G A|B4|c c c c|c B B B|B A A B|A2 d2|]"),
 ("Jingle Bells","jingle3",3,"Acompañamiento en clave de Fa","El bajo con acordes que sostiene el villancico; firme y alegre.",
   "4/4","1/4","G","[K:clef=bass] G,, [DG] [DG] [DG]|C, [EG] [EG] [EG]|D, [DF] [DF] [DF]|G,, [DG]2 z|]"),
 ("Jingle Bells","jingle4",4,"El estribillo en corcheas","«Jingle bells, jingle bells» completo en corcheas; ligero y a buen tempo.",
   "4/4","1/8","G","B2 B2 B4|B2 B2 B4|B2 d2 G2 A2|B6 z2|c2 c2 c2 c2|c2 B2 B2 B2|B2 A2 A2 B2|A4 d4|]"),
 ("We Wish You a Merry Christmas","wewish1",1,"Bajo-acorde de vals (clave de Fa)","Acompañamiento de vals sobre la vuelta completa: bajo en «1», acorde en «2-3».",
   "3/4","1/4","G","[K:clef=bass] G,, [B,D] [B,D]|C, [CE] [CE]|D, [DF] [DF]|G,, [B,D] [B,D]|E, [CE] [CE]|A,, [CE] [CE]|D, [DF] [DF]|G,,2 z|]"),
 ("We Wish You a Merry Christmas","wewish2",2,"Séptimas dominantes y su resolución","Cadena de séptimas que resuelven; escucha cómo cada una «tira» hacia el siguiente.",
   "4/4","1/4","G","[A^CEG]2 [DFAd]2|[E^GBd]2 [A^Ce]2|[D^FAc]2 [GBd]2|[A^CEG]2 [DFAd]2|]"),
 ("We Wish You a Merry Christmas","wewish3",3,"El tema del vals","La melodía «We wish you» que sube en oleadas; balanceo ternario.",
   "3/4","1/4","G","D|G G A|G F E|E E A|A G F|F F B|B A G|E c B|G3|]"),
 ("We Wish You a Merry Christmas","wewish4",4,"Vals a dos manos alternas","Bajo grave y acorde arpegiado en corcheas; el vaivén completo del vals.",
   "3/4","1/8","G","[K:clef=bass] G,,2 B,2 D2|C,2 E2 G2|D,2 F2 A2|G,,2 D2 B,2|E,2 G2 c2|A,,2 C2 E2|D,2 F2 A2|G,,4 z2|]"),
 ("Trouble","trouble1",1,"Arpegios de los cuatro acordes","Desgrana G-Em-C-D como acompañamiento continuo; que las notas fluyan igual.",
   "4/4","1/8","G","G B d B G B d B|E G B G E G B G|C E G E C E G E|D F A F D F A F|G B d B G B d g|G4 z4|]"),
 ("Trouble","trouble2",2,"La vuelta de acordes","La progresión en bloques con el giro a Am/F que ensombrece; cambia a tiempo.",
   "4/4","1/4","G","[G,B,D]2 [E,G,B,]2|[C,E,G,]2 [D,F,A,]2|[G,B,D]2 [E,G,B,]2|[A,CE]2 [D,F,A,]2|[G,B,D]4|]"),
 ("Trouble","trouble3",3,"Bajo en clave de Fa","La línea de bajo que camina bajo los acordes; firme y con dirección.",
   "4/4","1/4","G","[K:clef=bass] G,,2 E,2|C,2 D,2|G,,2 E,2|A,,2 D,2|B,,2 C,2|D,2 D,2|G,,4|G,,4|]"),
 ("Trouble","trouble4",4,"Arpegios rotos en semicorcheas","Estudio veloz de arpegios por la vuelta; regularidad y control.",
   "4/4","1/16","G","G B d g d B G B E G B e B G E G|C E G c G E C E D F A d A F D F|G4 z4 z8|]"),
 ("Eye of the Tiger","eye1",1,"Power chords deslizantes (clave de Fa)","Quintas sin tercera que se deslizan por la tonalidad; seco y contundente.",
   "4/4","1/4","Cm","[K:clef=bass] [C,G,]2 [C,G,]2|[B,,F,]2 [A,,E,]2|[C,G,]2 [C,G,]2|[F,,C,]2 [G,,D,]2|[C,G,]2 [B,,F,]2|[C,G,]4|]"),
 ("Eye of the Tiger","eye2",2,"Ritmo sincopado","Estudio de síncopa: ataca las notas justo DESPUÉS del pulso. Marca el tiempo con el pie.",
   "4/4","1/8","Cm","C z C C z C C z|C z C C z C z2|G z G G z G G z|G z G G z G z2|C z C E z C C z|C4 z4|]"),
 ("Eye of the Tiger","eye3",3,"El riff completo","El riff de la canción con su síncopa y sus power chords; con actitud.",
   "4/4","1/8","Cm","C3 C C3 C|C2 _B,2 C4|C3 C C3 _D|C2 _B,2 G,4|]"),
 ("Eye of the Tiger","eye4",4,"Escala de Do menor a dos octavas","La escala de la tonalidad (Mib-Lab-Sib) en corcheas, subiendo y bajando.",
   "4/4","1/8","Cm","C D E F G A B c|d e f g a b c' d'|d' c' b a g f e d|c B A G F E D C|]"),
 ("The Beginner","beginner1",1,"Apoyaturas","Estudio de la nota de adorno: rapidísima antes de cada nota principal, sin robarle tiempo.",
   "3/4","1/4","C","{D}E2 {F}E|{D}E {C}D2|{F}G2 {A}G|{F}G {E}F2|{D}E {C}D {B,}C|{B,}C {D}E {F}G|{A}G2 {F}E|C3|]"),
 ("The Beginner","beginner2",2,"Vals a tres tiempos","Melodía de vals ligera; no pises los tiempos débiles, deja que el «2-3» flote.",
   "3/4","1/4","C","C2 E|G2 E|C E G|c3|G2 F|E2 D|C E G|C3|]"),
 ("The Beginner","beginner3",3,"Motivos ligados con adorno","Frases cortas ligadas rematadas con apoyatura; el estilo del Primo.",
   "3/4","1/4","C","(C E) {F}E|(D F) {G}F|(E G) {A}G|c3|(G E) {F}E|(F D) {E}D|(E C) D|C3|]"),
 ("The Beginner","beginner4",4,"Apoyaturas dobles en corcheas","Adornos por ambos lados (desde abajo y desde arriba); ligereza y precisión.",
   "3/4","1/8","C","{D}E2 {F}E2 {D}E2|{C}D2 {E}D2 D2|{F}G2 {A}G2 {F}G2|{E}F2 {G}F2 F2|{D}E2 {C}D2 {B,}C2|C6|]"),
 ("Sonatina en La menor","sonatina_a1",1,"Tónica y dominante","Alterna La menor (reposo) y Mi (tensión, Sol#) y cierra la cadencia; el imán de la dominante.",
   "4/4","1/4","Am","[A,CE]2 [E,^G,B,]2|[A,CE]2 [E,^G,B,]2|[A,CE] [D,F,A,] [E,^G,B,] [A,CE]|[D,F,A,]2 [E,^G,B,]2|[A,CE]4|]"),
 ("Sonatina en La menor","sonatina_a2",2,"Arpegio menor, dos octavas","El acorde de La menor desgranado subiendo y bajando dos octavas; parejo y relajado.",
   "4/4","1/8","Am","A, C E A E C A, C|A, C E A c e a2|a e c A c e c A|A,2 E2 A,2 z2|]"),
 ("Sonatina en La menor","sonatina_a3",3,"Escala menor armónica","La escala de La menor con Sol# (sensible); sube y baja sintiendo la tensión.",
   "4/4","1/8","Am","A, B, C D E F ^G A|A ^G F E D C B, A,|A, B, C D E F ^G A|A2 z2 z4|]"),
 ("Sonatina en La menor","sonatina_a4",4,"El giro a Do mayor","Estudio del paso al relativo mayor: de La menor a la luz de Do.",
   "4/4","1/4","Am","[A,CE] [A,CE] [D,F,A,] [E,^G,B,]|[A,CE]2 [C,E,G,]2|[F,A,C] [G,B,D] [C,E,G,] [C,E,G,]|[C,E,G,]4|]"),
 ("Heart and Soul","heart1",1,"El bucle de cuatro acordes (clave de Fa)","La vuelta I-vi-IV-V que se repite en toda la canción; memorízala.",
   "4/4","1/4","C","[K:clef=bass] [C,E,G,]2 [A,,C,E,]2|[F,,A,,C,]2 [G,,B,,D,]2|[C,E,G,]2 [A,,C,E,]2|[F,,A,,C,]2 [G,,B,,D,]2|[C,E,G,]4|]"),
 ("Heart and Soul","heart2",2,"Síncopa de la melodía","La melodía que entra a contratiempo sobre el bucle; ataca en los huecos, no en el pulso.",
   "4/4","1/8","C","z E E z G G z c|z c c z G G z E|z E E z G G z c|z G G z e e z c|c2 z2 z4|]"),
 ("Heart and Soul","heart3",3,"El tema completo","La melodía de Heart and Soul con su swing; balancea, no la toques recta.",
   "4/4","1/4","C","E E E E|E F G2|C C C C|C D E2|D D D D|D E F2|E2 z2|G4|]"),
 ("Heart and Soul","heart4",4,"Improvisar sobre el bucle","Arpegios de los cuatro acordes en corcheas para improvisar encima; hazlo tuyo.",
   "4/4","1/8","C","C E G c G E C E|A, C E A E C A, C|F, A, C F C A, F, A,|G, B, D G D B, G, B,|]"),
 ("Greensleeves","greensleeves1",1,"Vals melancólico (clave de Fa)","Acompañamiento de vals en La menor: bajo en «1», acorde en «2-3»; sobre la vuelta completa.",
   "3/4","1/4","Am","[K:clef=bass] A,, [EA] [Ec]|E, [E^G] [EB]|F, [FA] [Fc]|C, [EG] [Ec]|D, [FA] [Fd]|A,, [EA] [Ec]|E, [E^G] [EB]|A,,2 z|]"),
 ("Greensleeves","greensleeves2",2,"El giro Am → E","Cadencia menor: de La menor a Mi mayor (con Sol#) y vuelta; la tensión que da color.",
   "4/4","1/4","Am","[A,CE]2 [E,^G,B,]2|[A,CE]2 [D,F,A,]2|[E,^G,B,]2 [A,CE]2|[A,CE] [E,^G,B,] [A,CE] [E,^G,B,]|[A,CE]4|]"),
 ("Greensleeves","greensleeves3",3,"El tema en 3/4","La célebre melodía de Greensleeves; frases largas que respiran en vals.",
   "3/4","1/4","Am","A|c2 d|e3/2 f/ e|d2 B|G3/2 A/ B|c2 A|A3/2 ^G/ A|B2 ^G|E3|]"),
 ("Greensleeves","greensleeves4",4,"Arpegios con pedal","Arpegios de Am y E en corcheas para practicar el cambio de pedal por acorde.",
   "3/4","1/8","Am","A, C E A c e|E, ^G, B, E ^G B|F, A, C F A c|E, ^G, B, E B ^G|A,4 z2|]"),
 ("Morning Song","morning1",1,"Dobles notas de sexta","Estudio de sextas: dos notas a la vez subiendo y bajando; ambas exactamente juntas.",
   "4/4","1/4","E","[CE][DF][EG][FA]|[GB][Ac][Bd][ce]|[ce][Bd][Ac][GB]|[FA][EG][DF][CE]|[CE][EG][GB][ce]|[CE]4|]"),
 ("Morning Song","morning2",2,"Escala de Mi mayor, dos octavas","Cuatro sostenidos (Fa#-Do#-Sol#-Re#); sube dos octavas y baja sintiendo las negras.",
   "4/4","1/4","E","E F G A|B c d e|e f g a|b2 e'2|e' b a g|f e d c|B A G F|E4|]"),
 ("Morning Song","morning3",3,"El tema de Grieg","La melodía del Amanecer que crece desde el silencio; suave y en ondas.",
   "4/4","1/4","E","B A G A|B d B A|G F G A|B2 z2|e d c d|e g e d|c B c d|e2 z2|]"),
 ("Morning Song","morning4",4,"Sextas en corcheas","Cadena de sextas en corcheas subiendo y bajando; deslízalas parejas y ligadas.",
   "4/4","1/8","E","[CE][DF][EG][FA][GB][Ac][Bd][ce]|[ce][Bd][Ac][GB][FA][EG][DF][CE]|[CE][EG][GB][ce][GB][EG][CE]2|]"),
 ("Shallow","shallow1",1,"Arpegio quebrado","Arpegios de acompañamiento subiendo por la vuelta; que suenen como un goteo regular.",
   "4/4","1/8","G","D G B G D G B G|E A c A E A c A|D G B G D G B G|C E G E C E G E|D F A F D F A d|G B d g d B G2|]"),
 ("Shallow","shallow2",2,"Entradas anticipadas","Estudio de anticipación: la melodía entra ANTES del tiempo (tras el silencio). Cuenta bien.",
   "4/4","1/4","G","z G G B|d2 z d|c B A2|z A A c|e2 z e|d c B2|z B d g|d2 z2|]"),
 ("Shallow","shallow3",3,"El estribillo","La melodía del estribillo que se eleva; crece con la frase hacia el agudo.",
   "4/4","1/4","G","D G B|d3/2 B/ G2|c e c|A3/2 c/ e2|d B G|A B d2|e d B|G4|]"),
 ("Shallow","shallow4",4,"Arpegios amplios en semicorcheas","Estudio veloz de arpegios de gran extensión; muñeca flexible y crescendo.",
   "4/4","1/16","G","G, D G B d B G D G, D G B d B G D|C, E G c e c G E A, E A c e c A E|G,4 z4 z8|]"),
 ("Lovely","lovely1",1,"Arpegio simétrico","Arpegios en espejo por varias tonalidades; sube y baja parejo, como reflejado.",
   "4/4","1/8","G","G B d g d B G B|A c e a e c A c|B d g b g d B d|E G B e B G E G|A, C E A E C A, C|G, B, D G D B, G,2|]"),
 ("Lovely","lovely2",2,"Melodía sostenida sobre arpegio","Notas largas y cantadas que flotan sobre el arpegio; escucha la línea por encima.",
   "4/4","1/4","G","d2 B2|d2 e2|d2 B2|c2 A2|B2 d2|e2 d2|B2 A2|G4|]"),
 ("Lovely","lovely3",3,"Giro a Mi menor","El paso al relativo menor, más íntimo; arpegios de Em y Bm suaves.",
   "4/4","1/8","G","E G B e B G E G|B, ^D ^F B ^F ^D B, ^D|E G B e B G E G|E4 z4|]"),
 ("Lovely","lovely4",4,"Arpegios en movimiento contrario","Estudio de arpegios que abren y cierran en semicorcheas; simetría y control.",
   "4/4","1/16","G","G B d g b g d B G B d g b g d B|A c e a c' a e c A c e a c' a e c|G4 z4 z8|]"),
 ("My Heart Will Go On","titanic1",1,"Legato profundo","Notas largas ligadas; hunde cada tecla hasta el fondo y no la sueltes hasta la siguiente.",
   "4/4","1/4","F","(F2 G2)|(A2 G2)|(F2 A2)|(c4)|(c2 d2)|(c2 A2)|(G2 F2)|(F4)|]"),
 ("My Heart Will Go On","titanic2",2,"Escala de Fa (Sib), dos octavas","Un solo bemol: toca el Sib cada vez que aparezca el Si. Sube dos octavas y baja.",
   "4/4","1/4","F","F G A B|c d e f|g a b c'|d'2 c'2|c' b a g|f e d c|B A G F|F4|]"),
 ("My Heart Will Go On","titanic3",3,"El tema de Titanic","La melodía con sus suspensiones; deja que cada nota larga cante y respire.",
   "4/4","1/4","F","C F G|A3/2 G/ F2|G A B|A3/2 G/ F2|C F G|A B c2|d c A|G F z|]"),
 ("My Heart Will Go On","titanic4",4,"Frase en arco con pedal","Estudio de fraseo por arcos: crece hacia el centro y se apaga; cambia el pedal por acorde.",
   "4/4","1/8","F","F2 A2 c2 f2|c2 A2 F4|G2 B2 d2 g2|d2 B2 G4|A2 c2 f2 a2|f2 c2 A4|G2 F2 C2 F2|F8|]"),
 ("Boig per tu","boig1",1,"Acordes en bloque","La vuelta de acordes de la balada, todos juntos y sostenidos, con sonido cálido y lleno.",
   "4/4","1/4","C","[CEG]2 [GBd]2|[A,CE]2 [FAc]2|[CEG]2 [GBd]2|[A,CE]2 [E,G,B,]2|[FAc]2 [GBd]2|[CEG]4|]"),
 ("Boig per tu","boig2",2,"Sostenidos de paso","Estudio cromático: notas alteradas que conectan la melodía; con naturalidad en la línea.",
   "4/4","1/8","C","C ^C D ^D E ^F G z|G ^F E ^D C z z2|C ^C D E ^F G ^G a|a ^g g ^f f e z2|]"),
 ("Boig per tu","boig3",3,"El tema de la balada","La melodía cantada de «Boig per tu»; sin prisa, dejando respirar cada frase.",
   "4/4","1/4","C","E G G|A3/2 G/ E2|D E G|E3/2 D/ C2|C E G|c3/2 B/ A2|G E D|C4|]"),
 ("Boig per tu","boig4",4,"Acordes arpegiados con bajo","Arpegia los acordes de la balada en corcheas con el bajo sostenido; legato y color.",
   "4/4","1/8","C","C E G c G E G c|A, C E A E C E A|F, A, C F C A, C F|G, B, D G D B, D G|C E G c e g c'2|]"),
 # ==================== MAESTRIA ====================
 ("Perfect","perfect1",1,"Arpegio en 6/8","Arpegio en el vaivén mecido de 6/8, recorriendo los acordes; regular, no rápido.",
   "6/8","1/8","G","G B d g d B|c e g e c A|G B d g d B|D F A d A F|G B d g b g|d B G G2 z|]"),
 ("Perfect","perfect2",2,"Balanceo de 6/8","Melodía en dos pulsos por compás (1-2-3 / 4-5-6); mécela, no la marches.",
   "6/8","1/8","G","G2 B d2 B|c2 A G3|d2 B g3|e2 c A3|G2 B d2 g|d2 B G3|]"),
 ("Perfect","perfect3",3,"El tema de Perfect","La melodía de la canción; frases suaves con el balanceo de la barcarola.",
   "6/8","1/8","G","D2 G A2 B|A2 G G3|D2 G A2 B|d2 c B3|e2 d B2 G|A2 G E3|D2 G B2 d|G6|]"),
 ("Perfect","perfect4",4,"Arpegios amplios en 6/8","Estudio de arpegios de gran extensión con el bajo; independencia y fluidez.",
   "6/8","1/8","G","[K:clef=bass] G,,B,D G,B,D|C,E,G C,E,G|D,F,A D,F,A|G,,B,D G,B,D|E,G,B, E,G,B,|A,,C,E A,,C,E|D,F,A D,F,A|G,,4 z2|]"),
 ("Believer","believer1",1,"Tresillos","Tresillos subiendo y bajando (Fa menor, 4 bemoles); tres notas iguales por tiempo.",
   "4/4","1/8","Fm","(3F G A (3B c d (3e f g (3f e d|(3c B A (3G F E (3F G A (3B c d|(3c d e (3f g a (3g f e (3d c B|(3c B A (3G F E (3F G A F2|]"),
 ("Believer","believer2",2,"Ostinato constante (clave de Fa)","El latido grave que no varía, moviéndose por la armonía; mecánico y firme.",
   "4/4","1/4","Fm","[K:clef=bass] F,2 C,2|F,2 C,2|F,2 C,2|C,2 C,2|D,2 A,,2|D,2 A,,2|F,2 C,2|F,4|]"),
 ("Believer","believer3",3,"El riff con tresillo","El motivo de la canción con su empuje de tresillos; fuerza contenida.",
   "4/4","1/8","Fm","F2 F (3F G A c2 c|(3c c c _B2 A2 F2|F2 F (3F G A c2 f|(3f e d c2 F4|]"),
 ("Believer","believer4",4,"Tres contra dos","Estudio de polirritmia: una mano tres notas, otra dos; muy lento hasta que encajen.",
   "4/4","1/4","Fm","(3F A c (3F A c|(3F A c (3F A c|(3C E G (3C E G|(3C E G (3C E G|]"),
 ("El Golpe (The Entertainer)","entertainer1",1,"Síncopa de ragtime","La melodía se adelanta al pulso; ese «cojeo» pícaro es el sabor del ragtime.",
   "2/4","1/8","C","D E C2|E F D2|E F G2|c2 z2|A c G2|E G C2|D E C2|C2 z2|]"),
 ("El Golpe (The Entertainer)","entertainer2",2,"Bajo-acorde (clave de Fa)","La izquierda «reloj»: grave y acorde alternos, firmes como un metrónomo.",
   "2/4","1/8","C","[K:clef=bass] C, [E,G,] G,, [E,G,]|C, [E,G,] G,, [E,G,]|F,, [A,C] C, [A,C]|F,, [A,C] C, [A,C]|G,, [D,G,] D,, [D,G,]|C, [E,G,] G,,2|]"),
 ("El Golpe (The Entertainer)","entertainer3",3,"El tema del Entertainer","El célebre tema de Joplin en semicorcheas sincopadas; ligero y saltarín.",
   "2/4","1/16","C","d3 c d3 e|c2 A2 z4|d3 c d3 e|c4 z4|d3 c d3 e|c2 e2 c2 A2|G2 A2 c2 d2|c4 z4|]"),
 ("El Golpe (The Entertainer)","entertainer4",4,"Síncopa contra bajo firme","Estudio de coordinación: melodía sincopada sobre el bajo regular; muy lento al principio.",
   "2/4","1/8","C","G/A/ G z G|A/c/ A z A|G/A/ G E/G/|c2 z2|E/G/ c z c|G/c/ e z e|d/c/ B/A/ G/F/ E/D/|C2 z2|]"),
 ("Primavera de Vivaldi","spring1",1,"Staccato veloz","Staccato ágil (Mi mayor); notas cortas como pájaros, subiendo por los acordes.",
   "4/4","1/8","E",".E .G .B .G .E .G .B .G|.F .A .c .A .F .A .c .A|.G .B .d .B .G .B .d .B|.E .G .B .e .B .G .E2|]"),
 ("Primavera de Vivaldi","spring2",2,"Acordes en bloque con eco","Acorde fuerte y su repetición suave, como pregunta y respuesta; recorre la armonía.",
   "4/4","1/4","E","[EGB][EGB] [Bdf][Bdf]|[EGB]2 z2|[Ace][Ace] [EGB][EGB]|[Ace]2 z2|[EGB] [Bdf] [EGB] [Bdf]|[EGB]4|]"),
 ("Primavera de Vivaldi","spring3",3,"El tema de La Primavera","La célebre melodía; brillante, alegre y precisa, con sus repeticiones en eco.",
   "4/4","1/8","E","E2 ^G2 B2 B2|B A B c B2 z2|E2 ^G2 B2 B2|B A B c B2 z2|d2 d2 d c B A|B2 e2 e2 z2|]"),
 ("Primavera de Vivaldi","spring4",4,"Escalas rápidas en semicorcheas","Estudio veloz de escalas de Mi mayor; ligereza, igualdad y staccato ágil.",
   "4/4","1/16","E","E F G A B c d e f g a b c' d' e' f'|f' e' d' c' b a g f e d c B A G F E|]"),
 ("Romance","romance1",1,"Frase cantábile","Legato cantábile: frases largas ligadas que respiran; canta con los dedos.",
   "4/4","1/4","G","(G2 A2)|(B2 c2)|(d2 B2)|(G4)|(e2 d2)|(c2 B2)|(A2 G2)|(G4)|]"),
 ("Romance","romance2",2,"Escala con matiz","Sube creciendo y baja apagando; la misma línea con dos dinámicas, para el fraseo.",
   "4/4","1/4","G","G A B c|d e f g|a g f e|d c B A|G A B c|d c B A|G F E D|G4|]"),
 ("Romance","romance3",3,"El canto del Primo","La melodía tierna del romance; dolce, con crescendo hacia el clímax y pp final.",
   "4/4","1/4","G","D G3/2 A/|B2 A2|G3/2 A/ B c|d3 B|e3/2 d/ c B|A2 G2|A3/2 G/ F A|G4|]"),
 ("Romance","romance4",4,"Giro a Mi menor con dinámicas","Estudio del color menor central; mismo tempo, otro carácter, con crescendo y diminuendo.",
   "4/4","1/8","G","E2 F2 ^G2 A2|B2 A2 ^G2 E2|B,2 ^D2 F2 A2|G2 F2 E4|e2 d2 c2 B2|A2 G2 F2 E2|E8|]"),
 ("Scherzo","scherzo1",1,"Staccato scherzando","La broma del scherzo en 3/4: notas secas y saltarinas subiendo y bajando; muñeca ligera.",
   "3/4","1/8","G",".G .B .d .B .G .B|.c .A .F .A .G .B|.d .g .d .B .G .d|.c .A .F .A .G2|.G .d .B .g .d .B|.G2 z2 z2|]"),
 ("Scherzo","scherzo2",2,"Tresillos del Trío (Mi bemol)","El Trío en Mi bemol (tres bemoles): tresillos iguales y suaves, subiendo por los acordes.",
   "3/4","1/8","Eb","(3E G B (3E G B (3E G B|(3F A c (3F A c (3F A c|(3G B e (3G B e (3G B e|(3E G B (3E G B (3E2 z|]"),
 ("Scherzo","scherzo3",3,"El tema del Scherzo","El motivo saltarín y bromista; staccato preciso y contrastes de dinámica.",
   "3/4","1/8","G","G2 .B .d G2|.c .A F2 z2|G2 .B .d g2|.d .B G2 z2|.e .c .A .f .d .B|.c .A .F G2 z|]"),
 ("Scherzo","scherzo4",4,"La transición Sol → Mib","Estudio del enlace del Scherzo al Trío: reubica la mano sobre las negras (Mib-Lab-Sib).",
   "3/4","1/8","Eb","G2 .B .d .G .B|.c .A .F2 z2|E2 G2 B2|e2 c2 A2|G2 F2 E2|E4 z2|]"),
 ("Sonatina en Sol mayor","sonatina_g1",1,"Melodía en blancas","Notas largas (blancas): cuéntalas enteras para que caigan sobre el acompañamiento.",
   "4/4","1/4","G","G2 B2|d2 B2|c2 A2|G2 G2|B2 d2|g2 d2|B2 A2|G4|]"),
 ("Sonatina en Sol mayor","sonatina_g2",2,"Bajo-acorde (clave de Fa)","El acompañamiento a cuatro manos: bajo grave y acordes staccato del Piano 2.",
   "4/4","1/4","G","[K:clef=bass] G,, [DGB] [DGB] [DGB]|D, [DFA] [DFA] [DFA]|C, [CEG] [CEG] [CEG]|G,, [DGB] [DGB] [DGB]|A,, [CEA] [CEA] [CEA]|D, [DFA]2 z|]"),
 ("Sonatina en Sol mayor","sonatina_g3",3,"La melodía del Piano 1","La línea cantada de la sonatina; clásica, serena y bien medida.",
   "4/4","1/4","G","d2 B2|c2 A2|B2 G2|A4|d2 e2|d2 B2|c2 A2|G4|]"),
 ("Sonatina en Sol mayor","sonatina_g4",4,"Escala de Sol en corcheas","La escala de la tonalidad a dos octavas con Fa#; base del lenguaje de la pieza.",
   "4/4","1/8","G","G A B c d e ^f g|a b c' d' e' ^f' g'2|g' ^f' e' d' c' b a g|^f e d c B A G2|]"),
 ("Para Elisa","elisa1",1,"Alternancia Mi–Re#","El temblor de apertura de Für Elise: alterna Mi y Re# ligero y sin acento, en 3/8.",
   "3/8","1/16","Am","e ^d e ^d e B|d c A2 z2|e ^d e ^d e B|d c A2 z2|]"),
 ("Para Elisa","elisa2",2,"Arpegios de la izquierda (clave de Fa)","El acompañamiento desgranado en 3/8 recorriendo La menor y Mi; suave y regular.",
   "3/8","1/16","Am","[K:clef=bass] A,, E, A, E, A, E,|E,, E, ^G, E, ^G, E,|A,, E, A, E, A, E,|A,,2 E,2 A,2|]"),
 ("Para Elisa","elisa3",3,"El tema A completo","La melodía célebre de Für Elise; corcheas continuas ligeras entre las dos manos.",
   "3/8","1/16","Am","e ^d e ^d e B|d c A2 z2|C E A B2 z|B c e2 z2|c e ^d e ^d e|B2 z4|]"),
 ("Para Elisa","elisa4",4,"Corcheas continuas en semicorcheas","Estudio de fluidez: semicorcheas seguidas con las dos manos en 3/8, sin acelerar.",
   "3/8","1/16","Am","A c e a e c|A c e a e c|B d ^f a ^f d|B d ^f a ^f d|A c e a e c|A4 z2|]"),
]

manifest={}
for base,eid,level,title,instr,M,L,K,body in EX:
    if body.startswith("[K:clef=bass] "):
        K=K+" clef=bass"; body=body[len("[K:clef=bass] "):]
    a=buildabc(M,L,K,body)
    try:
        sz=render(a, f"ex_{eid}.png")
    except Exception as e:
        print("ERROR", eid, e); sz=None
    manifest.setdefault(base,[]).append({"id":eid,"level":level,"title":title,"instr":instr})

json.dump(manifest, open("exercises.json","w",encoding="utf-8"), ensure_ascii=False, indent=1)
print("LISTO ·", sum(len(v) for v in manifest.values()), "ejercicios ·", len(manifest), "piezas")
